server:
  port: 8084

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

#        - id: HotelService
#          uri: lb://HOTELSERVICE
#          predicates:
#            - Path=/hotels/**
#
#        - id: RatingService
#          uri: lb://RATINGSERVICE
#          predicates:
#            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
